# Generated by Django 4.2 on 2026-03-24 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_number', models.CharField(max_length=10, unique=True, verbose_name='VIP 編號')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp 號碼')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已驗證')),
                ('verification_code', models.CharField(blank=True, max_length=6, verbose_name='驗證碼')),
                ('code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='驗證碼過期時間')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='驗證時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_profile', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': 'VIP 用戶',
                'verbose_name_plural': 'VIP 用戶',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案例標題')),
                ('category', models.CharField(choices=[('career', '事業'), ('wealth', '財運'), ('relationship', '感情'), ('health', '健康'), ('other', '其他')], default='career', max_length=20, verbose_name='類別')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齡')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('', '不詳')], max_length=1, verbose_name='性別')),
                ('sub_type', models.CharField(blank=True, max_length=50, verbose_name='細分場景')),
                ('requester_type', models.CharField(blank=True, max_length=20, verbose_name='求測人類型')),
                ('has_supervisor', models.BooleanField(blank=True, null=True, verbose_name='是否有直接上司')),
                ('has_competitor', models.BooleanField(blank=True, null=True, verbose_name='是否有競爭對手')),
                ('has_investment', models.BooleanField(blank=True, null=True, verbose_name='是否有資金投入')),
                ('manual_time', models.DateTimeField(blank=True, null=True, verbose_name='問事時間（起心動念）')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('solar_time_used', models.DateTimeField(blank=True, null=True, verbose_name='實際使用太陽時')),
                ('question', models.TextField(blank=True, verbose_name='問事問題')),
                ('question_data', models.JSONField(default=dict, verbose_name='問題數據')),
                ('chart_data', models.JSONField(default=dict, verbose_name='盤面數據')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI 分析')),
                ('feedback_required', models.BooleanField(default=False, verbose_name='需要反饋')),
                ('feedback_submitted', models.BooleanField(default=False, verbose_name='已提交反饋')),
                ('feedback_result', models.CharField(blank=True, choices=[('accurate', '準確'), ('partial', '部分準確'), ('inaccurate', '不準確'), ('pending', '待驗證')], max_length=20, verbose_name='反饋結果')),
                ('feedback_comment', models.TextField(blank=True, verbose_name='反饋說明')),
                ('feedback_time', models.DateTimeField(blank=True, null=True, verbose_name='反饋時間')),
                ('is_historical', models.BooleanField(default=False, verbose_name='是否歷史案例')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='資料來源')),
                ('ganzhi', models.CharField(blank=True, max_length=100, verbose_name='干支八字')),
                ('key_config', models.TextField(blank=True, verbose_name='關鍵格局')),
                ('expert_judgment', models.TextField(blank=True, verbose_name='大師斷語')),
                ('real_feedback', models.TextField(blank=True, verbose_name='事後反饋')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶')),
            ],
            options={
                'verbose_name': '問事案例',
                'verbose_name_plural': '問事案例',
                'ordering': ['-created_at'],
            },
        ),
    ]
